name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 || true

    - name: Run tests
      run: |
        pytest -q

    - name: Build Docker image
      run: |
        docker build -t ia-arquitetura-base:${{ github.sha }} .

    - name: Docker Hub Push (optional)
      if: github.event_name == 'push' && secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        docker tag ia-arquitetura-base:${{ github.sha }} $DOCKERHUB_USERNAME/ia-arquitetura-base:latest
        docker push $DOCKERHUB_USERNAME/ia-arquitetura-base:latest
